### ISSUE TITLE
Type error on CroctProvider

### ISSUE THREAD

**Issue by joaopaulomoraes** [croct-tech/plug-react#177]
## 🐞 Bug report

A type error in the latest version prevents the application from starting or building correctly. The problem appeared apparently after updating the react/typescript packages.

### Steps to reproduce
Install the latest version with `npm install @croct/plug-react@latest` in a typescript project (recent version) to get the error.
Tested in a nextjs and reactjs application.

### Screenshots

<img width="751" alt="Screen Shot 2022-06-14 at 20 47 44" src="https://user-images.githubusercontent.com/16243531/173707569-6fe1095b-6abe-4417-8732-4967f621a63c.png">

### Additional context

```
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 480.76 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.15.1 - /usr/local/opt/node@16/bin/node
    npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
Browsers:
    Chrome: 102.0.5005.115
npmPackages:
    @babel/preset-typescript: ^7.17.12 => 7.17.12
    @croct/plug-react: ^0.4.0 => 0.4.0
    next: ^12.1.6 => 12.1.6
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
    typescript: ^4.7.3 => 4.7.3
```

**Comment by marcospassos** [comment]
Fixed in #178
